language: node_js
# Make the filesystem case insensitive.... Because one of the lib we use is defective.... react-data-menu
os:
  - osx
node_js:
  - "4"
cache:
  timeout: 500
  directories:
    - node_modules
script:
    - npm run build
notifications:
  email: false
deploy:
    - provider: script
      skip_cleanup: true
      script: node ./dist/ftpdeploy.js --user ${BETA_FTP_USER} --password ${BETA_FTP_PWD} --use_strict
      on:
        tags: true
        all_branches: true
      condition: "$TRAVIS_TAG =~ .*beta.*$"
    - provider: script
      skip_cleanup: true
      script: node ./dist/ftpdeploy.js --user ${DEMO_FTP_USER} --password ${DEMO_FTP_PWD} --use_strict
      on:
        tags: true
        all_branches: true
        condition: "$TRAVIS_TAG =~ ^((?!beta).)*$"