language: node_js
# Make the filesystem case insensitive.... Because one of the lib we use is defective.... react-data-menu
os:
  - osx
node_js:
  - "4"
cache:
  timeout: 1000
  directories:
    - node_modules
script:
    - npm run build
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh "/public_html/beta/"
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ .*beta.*$"