name: RELEASE

on:
  push:
    branches:
      - dev
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    env:
      AG_GRID_LICENSE: ${{ secrets.AG_GRID_LICENSE }}
      ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
      IPUSHPULL_USERNAME: ${{ secrets.IPUSHPULL_USERNAME }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      VALID_BLOTTER_LICENSE: ${{ secrets.VALID_BLOTTER_LICENSE }}

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2
        with:
          path: demo

      - name: setup .npmrc
        uses: './demo/.github/actions/set-npmrc'
        working-directory: demo

      - name: Echo whoami
        run: npm whoami --registry=https://registry.adaptabletools.com
        working-directory: demo

      - name: Executing npm install
        run: npm i
        working-directory: demo

      - name: Building
        run: npm run build
        working-directory: demo
        env:
          CI: true

      - name: echo COMMIT_MESSAGE
        run: echo ${COMMIT_MESSAGE}

      - name: checkout adaptable-demo-dist repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AB_DEPLOY_GITHUB_TOKEN }}
          repository: AdaptableTools/adaptable-demo-dist
          path: demo-dist

      - name: move dist to demo-dist
        run: rm -fr demo-dist/dist && mv demo/dist demo-dist

      - uses: './demo/.github/actions/git-push-action'
        name: Push changes
        with:
          github_token: ${{ secrets.AB_DEPLOY_GITHUB_TOKEN }}
          branch: master
          directory: demo-dist
          repository: AdaptableTools/adaptable-demo-dist
          commit_message: ${COMMIT_MESSAGE}
